### ISSUE TITLE
下载此电子书时出现下到一半后报错退出

### ISSUE THREAD

**Issue by arandintday** [banjiaojuhao/epub-download-rs#1]
非常不好意思再次打扰你，我今天下载这个电子书的时候出现了标题中的情况，报错信息由于程序自动退出的太快看不清，我猜应该是本书的opf文件中存在类似于href="images/00209.jpg"的链接导致程序无法正常解析导致的
附上书籍地址：http://reader.epubee.com/books/mobile/77/77a9e6a05f4f31656abc064976a2addf/index_split_000.html

Edit：已解决，感谢

**Comment by banjiaojuhao** [comment]
网站有的页面是没有转码的，程序按照转码的处理了，所以出错。修复版本：
https://github.com/banjiaojuhao/epub-download-rs/releases/tag/v1.1
